### PR TITLE
Code simplification and remove PHP

### PR DESCRIPTION
**Pull request by edalzell**
I have modified the code to use the built-in helpers, etc
I also got rid of all PHP in the template file so that it can be modified much easier and familiar (standard Statamic template now).
Changed the format of the theme.yaml data so that it can be used on the template.
Added plugin and API.

### CODE REVIEW

**Comment by brettdewoody** [comment]
Thanks for taking the time to update the add-on. The only thing I see that might need attention is the changes to `_add-ons/theme.yaml`. Are those global variables specific to your theme? Or are they now standard in the Statamic base themes?

**Comment by edalzell** [comment]
oh, ya, sorry, those are specific for our theme. But they're there to show how they have to be formatted to work.

If that doesn't fit with your vision, no worries, we'll just use it in our project. Should give some ideas of how to simplify though.

**Comment by brettdewoody** [comment]
If you can remove the `theme.yaml` file I think everything looks great and I'll merge it. I think the community would find the update really helpful.

**Comment by edalzell** [comment]
You'll need to update the sample then right? The format you had previously can't be iterated through in the new template.

**Comment by brettdewoody** [comment]
Feel free to update the `README` with the new sample code. If not I can do that after merging.

**Pull request merged**
